[package]
name = "gerber-types"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]

[dependencies]
clippy = {version = "~0.0.79", optional = true}
chrono = "0.2"
uuid = "0.2"

[features]
nightly = ["clippy"]
